### ISSUE TITLE
Can No Longer Get Streaming URLs

### ISSUE THREAD

**Issue by abettadapur** [xissy/node-grooveshark-streaming#2]
Calling getStreamingUrl() crashes the program with 

ReferenceError: document is not defined
  at Request.eval (<anonymous>:13:20)
  at Request._callback (C:\www\nodegrooverio\node_modules\grooveshark-streaming\
lib\Grooveshark.coffee:67:7)
  at Request.self.callback (C:\www\nodegrooverio\node_modules\grooveshark-stream
ing\node_modules\request\index.js:142:22)
  at Request.EventEmitter.emit (events.js:98:17)
  at Request.<anonymous> (C:\www\nodegrooverio\node_modules\grooveshark-streamin
g\node_modules\request\index.js:856:14)
  at Request.EventEmitter.emit (events.js:117:20)
  at IncomingMessage.<anonymous> (C:\www\nodegrooverio\node_modules\grooveshark-
streaming\node_modules\request\index.js:808:12)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:910:16
  at process._tickCallback (node.js:415:13)

**Comment by xissy** [comment]
Thank you so much! Fixed. 4b21e0821a328841b6ab054a7a68bb6e6012be02
